// Copyright 2026 The Bedrock Authors
// This Source Code Form is subject to the terms of the Mozilla Public License,
// v. 2.0. If a copy of the MPL was not distributed with this file, You can
// obtain one at https://mozilla.org/MPL/2.0/.
//
// Fuzzes bookmark import (roadmap item 43: storage/parsers). Users import HTML
// exported by other browsers, downloaded from forums, or generated by scripts;
// the parser has to survive all of it.

#include "bedrock/fuzz/fuzz_main.h"

#include <string>

#include "bedrock/data/bookmark_store.h"

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
  const std::string html(reinterpret_cast<const char*>(data), size);
  bedrock::data::BookmarkStore store;
  store.ImportHtml(html);
  store.ExportHtml();  // a round trip must not crash either
  return 0;
}
