#!/usr/bin/env python3
"""Generate src_overrides/bedrock/ui/tokens.css from branding/design-tokens.json.

The tokens file is the single source of truth for the interface (item 26). The
moment a WebUI page writes `#0B0C0D` in its own stylesheet, there are two
palettes and one of them starts drifting. So the stylesheet is generated, never
edited, and the gate below fails the build if the checked-in file and the tokens
disagree.

Dark is the default theme, not a preference: `:root` carries the dark values and
stays dark whatever the OS says. `[data-theme="light"]` switches to the light
set, `[data-theme="dark"]` forces dark, and `[data-theme="system"]` is the only
selector that follows `prefers-color-scheme` — because "System" is a choice the
user makes in setup (item 98), not a default we take behind their back.

Usage:
  python3 scripts/gen_theme_css.py --write     # regenerate
  python3 scripts/gen_theme_css.py             # gate: fail if stale
  python3 scripts/gen_theme_css.py --selftest
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOKENS = ROOT / "branding/design-tokens.json"
OUT = ROOT / "src_overrides/bedrock/ui/tokens.css"

HEADER = """/* Generated by scripts/gen_theme_css.py from branding/design-tokens.json.
   Do not edit: edit the tokens and regenerate. */
"""


FACES = """/* Vendored under the SIL Open Font License; see branding/fonts/ and
   docs/THIRD_PARTY.md. Bundled, never fetched: a UI font pulled from a CDN
   would be a request to a third party on every window Bedrock opens. */
@font-face{font-family:Inter;font-weight:400;font-style:normal;font-display:swap;
  src:url(fonts/Inter-400.woff2) format('woff2')}
@font-face{font-family:Inter;font-weight:500;font-style:normal;font-display:swap;
  src:url(fonts/Inter-500.woff2) format('woff2')}
@font-face{font-family:Inter;font-weight:600;font-style:normal;font-display:swap;
  src:url(fonts/Inter-600.woff2) format('woff2')}
@font-face{font-family:Poppins;font-weight:500;font-style:normal;font-display:swap;
  src:url(fonts/Poppins-500.woff2) format('woff2')}
@font-face{font-family:Poppins;font-weight:600;font-style:normal;font-display:swap;
  src:url(fonts/Poppins-600.woff2) format('woff2')}

"""


def block(values: dict[str, str], indent: str = "  ") -> str:
    return "".join(f"{indent}--{name}: {value};\n" for name, value in values.items())


def colors(theme: dict[str, str]) -> dict[str, str]:
    return {name: value for name, value in theme.items()}


def render(tokens: dict) -> str:
    type_ = tokens["typography"]
    flat = {
        "font-ui": type_["family-ui"],
        "font-display": type_["family-display"],
        "font-mono": type_["family-mono"],
        "line-height": str(type_["line-height"]),
        "tracking-tight": type_["letter-spacing-tight"],
    }
    for name, px in type_["scale"].items():
        flat[f"text-{name}"] = f"{px}px"
    for name, weight in type_["weight"].items():
        flat[f"weight-{name}"] = str(weight)
    for step in tokens["space"]["scale"]:
        flat[f"space-{step}"] = f"{step}px"
    for name, px in tokens["radius"].items():
        flat[f"radius-{name}"] = f"{px}px"
    for name, shadow in tokens["elevation"].items():
        flat[f"elevation-{name}"] = shadow
    for name, motion in tokens["motion"].items():
        if name != "reduced-motion":
            flat[f"motion-{name}"] = motion
    for name, px in tokens["density"].items():
        flat[name] = f"{px}px"

    dark = colors(tokens["color"]["dark"])
    light = colors(tokens["color"]["light"])
    return (
        HEADER
        + "\n"
        + FACES
        + ":root {\n"
        + block(dark)
        + "\n"
        + block(flat)
        + "}\n\n"
        + '[data-theme="system"] {\n'
        + block(dark)
        + "}\n\n"
        + "@media (prefers-color-scheme: light) {\n"
        + '  [data-theme="system"] {\n'
        + block(light, "    ")
        + "  }\n}\n\n"
        + '[data-theme="light"] {\n'
        + block(light)
        + "}\n\n"
        + '[data-theme="dark"] {\n'
        + block(dark)
        + "}\n\n"
        + "@media (prefers-reduced-motion: reduce) {\n"
        + "  :root {\n"
        + "".join(
            f"    --motion-{name}: 0ms;\n"
            for name in tokens["motion"]
            if name != "reduced-motion"
        )
        + "  }\n}\n"
    )


def main() -> int:
    tokens = json.loads(TOKENS.read_text())
    css = render(tokens)

    if "--selftest" in sys.argv:
        assert "--surface: " in css and "--accent: " in css, "colours missing"
        assert css.count("[data-theme=") == 4, "light, dark and system selectors expected"
        assert "prefers-reduced-motion" in css, "reduced motion missing"
        assert "@font-face" in css and "fonts/Poppins-600.woff2" in css, "fonts missing"
        assert "https://" not in css, "a UI font must never be fetched at runtime"
        broken = dict(tokens)
        broken["motion"] = {"reduced-motion": "x"}
        assert "--motion-" not in render(broken), "motion vars should follow tokens"
        print("gen_theme_css selftest: ok")
        return 0

    if "--write" in sys.argv:
        OUT.write_text(css)
        print(f"wrote {OUT.relative_to(ROOT)}")
        return 0

    if not OUT.exists() or OUT.read_text() != css:
        print(
            "tokens.css is stale: run python3 scripts/gen_theme_css.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"tokens.css: ok ({len(tokens['color']['dark'])} colours, dark default)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
