#!/usr/bin/env python3
"""Generate (or verify) src_overrides/bedrock/BUILD.gn from the source tree.

The overlay is plain C++17 with no Chromium dependencies, so one source_set is
enough; hand-maintained per-directory targets drifted from the tree and no gate
caught it (the file still listed pre-item-47 paths after the layout move).

    python3 scripts/gen_build_gn.py           # verify, non-zero exit on drift
    python3 scripts/gen_build_gn.py --write   # regenerate
    python3 scripts/gen_build_gn.py --selftest
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BEDROCK = REPO / "src_overrides" / "bedrock"
BUILD_GN = BEDROCK / "BUILD.gn"

HEADER = """# Copyright 2026 The Bedrock Authors
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can
# obtain one at https://mozilla.org/MPL/2.0/.

# GENERATED by scripts/gen_build_gn.py -- do not edit by hand.
#
# The Bedrock overlay is dependency-free C++17: every file includes only the
# standard library and other bedrock/ headers, so a single source_set builds it
# with no intra-target dependency ordering to maintain. It is wired into the
# browser by patches/bedrock/build/0001-add-bedrock-to-chrome-browser.patch, which
# appends "//bedrock" to the //chrome/browser:browser deps.
#
# Excluded on purpose:
#   *_test.cc          host tests with their own main(), run by
#                      scripts/run_host_tests.sh (not a gtest target yet)
#   fuzz/*             each harness defines LLVMFuzzerTestOneInput and is built
#                      standalone by the same script

source_set("bedrock") {
  # Chromium's clang plugin requires raw_ptr<T> for pointer fields. raw_ptr
  # lives in //base, and depending on //base would make the overlay
  # unbuildable outside a Chromium checkout -- scripts/run_host_tests.sh
  # compiles all 106 files and 58 test/fuzz binaries with plain g++, which is
  # how every gate and every contributor without a 100 GB checkout runs the
  # suite. The eight raw pointers the plugin flags are non-owning
  # back-pointers between Bedrock policy objects that outlive them
  # (privacy/core/privacy_policy.h, privacy/network/https_policy.h,
  # profiles/profile_manager.h, profiles/new_identity.h); none of them point
  # at Chromium heap objects today. When a component starts holding a real
  # browser object, that component moves into its own target that does depend
  # on //base and does use raw_ptr. Tracked in docs/BUILD.md.
  configs -= [ "//build/config/clang:find_bad_constructs" ]

  sources = [
"""

FOOTER = """  ]
}
"""


def sources() -> list[str]:
    out = []
    for path in BEDROCK.rglob("*"):
        if path.suffix not in (".cc", ".h"):
            continue
        rel = path.relative_to(BEDROCK).as_posix()
        if rel.endswith("_test.cc") or rel.startswith("fuzz/"):
            continue
        out.append(rel)
    return sorted(out)


def render(files: list[str]) -> str:
    return HEADER + "".join(f'    "{f}",\n' for f in files) + FOOTER


def selftest() -> int:
    text = render(["a/b.cc", "a/b.h"])
    assert 'source_set("bedrock")' in text, text
    assert '    "a/b.cc",\n' in text, text
    assert text.endswith("  ]\n}\n"), text
    files = sources()
    assert files, "no overlay sources found"
    assert not [f for f in files if f.endswith("_test.cc")], "tests leaked in"
    assert not [f for f in files if f.startswith("fuzz/")], "fuzz harnesses leaked in"
    print("gen_build_gn selftest: ok")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest:
        return selftest()

    want = render(sources())
    if args.write:
        BUILD_GN.write_text(want)
        print(f"wrote {BUILD_GN.relative_to(REPO)} ({len(sources())} files)")
        return 0
    have = BUILD_GN.read_text() if BUILD_GN.exists() else ""
    if have != want:
        print(
            "BUILD.gn is out of date with the source tree.\n"
            "Run: python3 scripts/gen_build_gn.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"BUILD.gn: ok ({len(sources())} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
