#!/usr/bin/env python3
# Copyright 2026 The Bedrock Authors
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can
# obtain one at https://mozilla.org/MPL/2.0/.
"""Generate .ai/memory/MAP.md — the machine-written half of the project memory.

MAP.md is the file an agent reads to know *where* things are without opening
them. It is generated so it cannot drift: `scripts/check_memory.py` regenerates
it in CI and fails if the committed copy differs.

Hand-written memory (MEMORY.md, DECISIONS.md, HISTORY.md, INVARIANTS.md,
STATE.md) is never touched by this script.

Usage:
    python3 scripts/gen_memory.py            # write .ai/memory/MAP.md
    python3 scripts/gen_memory.py --stdout   # print, write nothing
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CODE_ROOT = os.path.join("src_overrides", "bedrock")
MODULES_JSON = os.path.join(".ai", "memory", "modules.json")
MAP_PATH = os.path.join(".ai", "memory", "MAP.md")

HEADER = """<!-- GENERATED by scripts/gen_memory.py — do not edit by hand.
     Regenerate with: python3 scripts/gen_memory.py -->

# Repository map (generated)

Tier 2 of the project memory: where code lives and which test covers it.
Read [../MEMORY.md](../MEMORY.md) first; open source files only after this map
told you which one you need.

"""


def read(path: str) -> str:
    with open(os.path.join(ROOT, path), encoding="utf-8") as handle:
        return handle.read()


def doc_sentence(path: str) -> str:
    """First sentence of a source file's leading doc comment.

    Skips the licence header and the include guard: the first comment block
    after them is what the author wrote to explain the file.
    """
    text = read(path)
    lines = text.splitlines()
    block: list[str] = []
    started = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("//"):
            body = stripped[2:].strip()
            if not started:
                if (
                    not body
                    or body.startswith("Copyright")
                    or "Mozilla Public License" in body
                    or body.startswith("v. 2.0")
                    or body.startswith("obtain one at")
                ):
                    continue
                started = True
            if started:
                if not body:
                    break
                block.append(body)
        elif started:
            break
        elif stripped.startswith(("#ifndef", "#define", "#include", "#pragma")) or not stripped:
            continue
    if not block:
        return ""
    joined = " ".join(block)
    sentence = re.split(r"(?<=[.!?])\s", joined)[0].strip()
    return re.sub(r"\s+", " ", sentence)


def module_dirs() -> list[str]:
    """Every directory holding source files, as a path relative to CODE_ROOT.

    The tree is nested since roadmap item 47 (ADR 0003), so a directory that
    only holds other directories is not a module.
    """
    base = os.path.join(ROOT, CODE_ROOT)
    found = []
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames.sort()
        if any(not f.startswith(".") for f in filenames):
            rel = os.path.relpath(dirpath, base).replace(os.sep, "/")
            if rel != ".":
                found.append(rel)
    return sorted(found)


def files_in(module: str) -> list[str]:
    base = os.path.join(ROOT, CODE_ROOT, module)
    return sorted(name for name in os.listdir(base) if os.path.isfile(os.path.join(base, name)))


def markdown_docs() -> list[str]:
    out = []
    for dirpath, dirnames, filenames in os.walk(os.path.join(ROOT, "docs")):
        dirnames.sort()
        for name in sorted(filenames):
            if name.endswith(".md"):
                rel = os.path.relpath(os.path.join(dirpath, name), ROOT)
                out.append(rel.replace(os.sep, "/"))
    return sorted(out)


def doc_title(rel: str) -> str:
    for line in read(rel).splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def gates() -> list[tuple[str, str]]:
    out = []
    for name in sorted(os.listdir(os.path.join(ROOT, "scripts"))):
        if not name.startswith("check_") or not name.endswith(".py"):
            continue
        rel = f"scripts/{name}"
        doc = ""
        text = read(rel)
        match = re.search(r'"""(.*?)(\n|""")', text, re.S)
        if match:
            doc = match.group(1).strip()
        out.append((rel, doc))
    return out


def build() -> str:
    modules = json.loads(read(MODULES_JSON))["modules"]
    parts = [HEADER]

    parts.append("## Code — `src_overrides/bedrock/`\n")
    parts.append(
        "New files mirrored into the Chromium tree layout. Preferred over patches "
        "(see ADR 0001). Every directory below is required to carry a summary in "
        "`.ai/memory/modules.json` and at least one `*_test.cc`.\n"
    )
    for module in module_dirs():
        summary = modules.get(module, {}).get("summary", "").strip()
        parts.append(f"\n### `{CODE_ROOT}/{module}/`\n")
        parts.append(f"{summary}\n\n")
        rows = ["| File | What it is |", "| --- | --- |"]
        for name in files_in(module):
            rel = f"{CODE_ROOT}/{module}/{name}"
            if name.endswith(".h") or (
                name.endswith(".cc") and not os.path.exists(os.path.join(ROOT, rel[:-3] + ".h"))
            ):
                what = doc_sentence(rel) or "—"
            elif name.endswith("_test.cc"):
                what = "tests"
            elif name.endswith(".cc"):
                what = "implementation"
            elif name.endswith(".json"):
                what = "data"
            else:
                what = "—"
            rows.append(f"| `{name}` | {what} |")
        parts.append("\n".join(rows) + "\n")

    parts.append("\n## Docs\n")
    rows = ["| File | Title |", "| --- | --- |"]
    for rel in markdown_docs():
        rows.append(f"| [`{rel}`]({os.path.relpath(rel, '.ai/memory')}) | {doc_title(rel)} |")
    parts.append("\n".join(rows) + "\n")

    parts.append("\n## CI gates — `scripts/`\n")
    parts.append("A gate is a rule the repository enforces on itself. Do not weaken one to make a change land.\n\n")
    rows = ["| Script | Enforces |", "| --- | --- |"]
    for rel, doc in gates():
        rows.append(f"| `{rel}` | {doc} |")
    rows.append("| `scripts/run_host_tests.sh` | Builds and runs every `*_test.cc` and fuzz smoke harness with plain g++. |")
    parts.append("\n".join(rows) + "\n")

    parts.append("\n## Elsewhere\n")
    parts.append(
        "```\n"
        "build/chromium.pin   pinned Chromium base revision\n"
        "build/sync.py        fetch Chromium + apply overlay\n"
        "build/args/*.gn      release, debug and sanitizer build configurations\n"
        "patches/             patches against the Chromium tree (last resort)\n"
        "THIRD_PARTY_NOTICES/ one notice file per dependency, 1:1 with the inventory\n"
        "branding/            name and logo assets\n"
        "```\n"
    )
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()
    content = build()
    if args.stdout:
        sys.stdout.write(content)
        return 0
    with open(os.path.join(ROOT, MAP_PATH), "w", encoding="utf-8") as handle:
        handle.write(content)
    print(f"wrote {MAP_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
